package BG.controller;
import java.awt.event.ActionListener;
import java.util.List;

import BG.Dice;
import BG.Glossary.Color;
import BG.Glossary.Side;

public abstract interface ViewInterface {
	public void start();
	public void subscribePointEvent(ActionListener listener);
	public void subscribeBearingEvent(ActionListener listener);
	public void subscribeExitEvent(ActionListener listener);
	public void subscribeRollEvent(ActionListener listener);
	public void subscribeRightClickEvent(ActionListener listener);
	public void subscribeUndoMoveEvent(ActionListener listener);
	public void subscribeMoveButton(ActionListener listener);
	public void subscribeBarEvent(ActionListener listener);
	public void subscribeDepthChange(ActionListener listener);
	public void subscribeMinimaxEvent(ActionListener listener);
	public void subscribeAlphabetaEvent(ActionListener listener);
	public void subscribeMoveForMeEvent(ActionListener listener);
	public void subscribeNewGameEvent(ActionListener listener);
	public void subscribeRestartEvent(ActionListener listener);
	public void notifyPlayerWin(Color color);
	public void setStatusBar(String string);
	public void setDepth(int depth);
	public void addLogInfo(String string);
	public void clearLog();
	public void selectFirstRoll(Color color);
	public void disableRoll(Color color);
	public void disableUndo();
	public void disableMove();
	public void disableDepth();
	public void disableMoveForeMe();
	public void enableMoveForeMe();
	public void enableDepth();
	public void enableRoll(Color color);
	public void enableUndo();
	public void enableMove();
	public void setPointCheckers(int point, Color color, int amount);
    public void setBar(Side side, Color color, int amount);
    public void setBotBearing(Color color, int amount);
    public void setTopBearing(Color color, int amount);
    public void setBearing(Side side, Color color, int amount);
    public void markPoint(int point);
    public void removeAllMarks();
    public void hightlightLastPointChecker(int point, Color color);
    public void removeHighlightFromPoint(int point, Color color);
    public void setDice(int d1, int d2);  
    public void removeDice();
    public int getLastPointClicked();
    public Side getLastBarClicked();
    public int getDepth();
    public void hightlightLastBarChecker(Side side, Color color);
    public void removeHighlightFromBar(Side side, Color color);
    public Dice getSelectedDice(Color color);
    public void setDiceOptions(List<Dice> dice, Color color);
    public void selectMinimax();
    public void selectAlphabeta();
}
